### ISSUE TITLE
Delete ChainID workaround in Nettest tests

### ISSUE THREAD

**Issue by dcastro** [tqtezos/stablecoin#109]
# Clarification and motivation

Because Nettest does not currently support retrieving the ChainID, we had to use a [workaround](https://github.com/tqtezos/stablecoin/blob/914392f6c3cdfe4cefeca784eb72c3baa6555d79/haskell/nettest/Permit.hs#L143-L161) in #108 to do this.

Once [morley/#356](https://gitlab.com/morley-framework/morley/-/issues/356) is implemented, we can delete this workaround

# Acceptance criteria

The workaround we use to retrieve the ChainId in the Permit nettests is deleted, and we're using the new function in Cleveland instead.

**Comment by gromakovsky** [comment]
Apparently this issue is unblocked now.
