### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/stablecoin#117]
# Clarification and motivation

There were some important changes after last release, the major one is Permit functionality.

# Acceptance criteria

A new release (1.3.0 I guess) is made according to the scheme used in this repo. I propose to include #110 into the next release as well.

**Comment by dcastro** [comment]
Release page: https://github.com/tqtezos/stablecoin/releases/tag/v1.3.0

**Comment by gromakovsky** [comment]
Cool, LGTM.
