### ISSUE TITLE
Document how to originate stablecoin.tz

### ISSUE THREAD

**Issue by mchaver** [tqtezos/stablecoin#133]
# Clarification and motivation

Document what the initial storage for stablecoin.tz should look like and include some origination examples.

# Acceptance criteria

Show how to originate the contract with storage. Explain initial values.

**Comment by gromakovsky** [comment]
@mchaver the recommended way to originate the contract is to use `stablecoin-client deploy` command. I have updated documentation to (hopefully) make it clearer, please take a look at https://github.com/tqtezos/stablecoin/pull/140 and let us know whether you using it is sufficient. Initial values are passed as command line options to `stablecoin-client deploy`.
