### ISSUE TITLE
More flexible metadata

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/stablecoin#138]
# Clarification and motivation

Currently we store all TZIP-16 metadata in the Stablecoin contract. This metadata is quite big, it caused origination operation of the contract to exceed the hard limit. I think there are two possible solutions:
1. TZIP-16 specifies that metadata can be stored in the original contract, in another contract (referred from the original one) or off-chain. Making sure metadata is accessible off-chain seems to be out of scope of `stablecoin-client`, while storing it in a separate contract seems very doable. I think that ideally the user should be able to choose where to store metadata. If it's requested to be stored in place, we originate the contract with all metadata in place. If it's requested to be stored separately, we originate two contracts. If the user wants to store it off-chain, they should put it into the right place and provide URIs.
2. Do deploy in two steps: first originate the contract with no metadata, then put it in the next step.

# Acceptance criteria

At least one of the above solutions is implemented.

We should implement everything mentioned above, unless there is a good reason not to do something.

**Comment by smondet** [comment]
> If the user wants to store it off-chain, they should put it into the right place and provide URIs.

This part is compatible with both solutions, and seems like a nice thing to always provide for the users (even if it is not the default, or it it is considered "expert mode").
