### ISSUE TITLE
Research LIGO with regards to tests and data layout in Michelson

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/stablecoin#17]
# Clarification and Motivation

We'd like to learn some things about LIGO:
1. What's the best/recommended way to write tests for contracts?
2. How can we define a data type that will have a certain type in Michelson. That's important to implement smart contracts that adhere to a certain standard, e. g. [FA2](https://gitlab.com/tzip/tzip/-/blob/131b46dd89675bf030489ded9b0b3f5834b70eb6/proposals/tzip-12/tzip-12.md). Apparently, LIGO does not guarantee any order even for types of 2 elements.

# Acceptance criteria

1. Research these topics yourself a bit.
2. Ask about these questions in #ligo in tezos-dev Slack to be sure we know the right answers and to add chances that LIGO developers will prioritize it.

**Comment by kkirka** [comment]
https://serokell.slack.com/archives/CUZCVM0N4/p1588159124083300

**Comment by awkure** [comment]
I believe we can close this issue

**Comment by gromakovsky** [comment]
We still have an unresolved question about printing lambdas from ligo code.

**Comment by gromakovsky** [comment]
Oh wait, I confused it with #15. Yes, we can close this one. The answers are:
1. There is no good way to tests contract offered by LIGO developers.
2. For layout we are already using this feature: https://gitlab.com/ligolang/ligo/-/merge_requests/585
