### ISSUE TITLE
Setup CI properly

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/stablecoin#20]
# Clarification and motivation

Our CI currently has several issues:
1. Uses `stack` to build Haskell code. We normally use `haskell.nix` instead, it works better.
2. Does not run `hlint`.
3. It does not compile LIGO code to produce Michelson.

Our tentative plan is to do #8 and #13, then do this issue. As result of #8 and #13, workflow should be the following: run `ligo` to produce `stablecoin.tz`, then run tests written in Haskell that require `stablecoin.tz`.

# Acceptance criteria

CI uses `haskell.nix` instead of `stack`, runs `hlint`, compiles LIGO code.

**Comment by balsoft** [comment]
Do we want to compile ligo on our CI or fetch a binary and run it?

**Comment by gromakovsky** [comment]
> Do we want to compile ligo on our CI or fetch a binary and run it?

That's up to you, but we definitely don't want to compile ligo on each run. We want to do `ligo compile-contract stablecoin/core.ligo main`. They way you get `ligo` executable does not matter, as long as it (I mean getting `ligo`) is done ≈immediately in ≥99% runs.

**Comment by balsoft** [comment]
Can't guarantee >99%, but will try to reduce the number of rebuilds.

**Comment by gromakovsky** [comment]
Well, it depends on frequency of builds, but the idea is that it should be rebuilt only if something extraordinary happens (e. g. no space left on some device or we want to switch to a new version).

**Comment by balsoft** [comment]
Yes, the way I'm setting it up it will only rebuild when you update with `niv update ligo` .

**Comment by gromakovsky** [comment]
As part of this issue please remove:
1. `shell.nix` and its mentions.
2. `test-ci` targets and everything that is used only by them (`STACK_CI_TEST_OPTIONS`).
