### ISSUE TITLE
[BUG] `stablecoin-client deploy` fails when the alias already exists

### ISSUE THREAD

**Issue by dcastro** [tqtezos/stablecoin#200]
# Description

The `stablecoin-client deploy` command originates two contracts: the metadata and the stablecoin contracts.

If the alias for these contracts don't yet exist, this command will create them.

If they do exist, the command is supposed to:
* Originate both contracts, using `odReplaceExisting = False` to tell morley-client not to create aliases
* At the end, [after both contracts have been successfully originated](https://github.com/tqtezos/stablecoin/blob/bc167c9d043dbcb0d95c297e0b73fde7cf314ee4/haskell/src/Stablecoin/Client/Main.hs#L68-L84):
  * If the user specified `--replace-alias`: forcefully replace the existing alias of the stablecoin contract.
  * Otherwise: interactively ask the user if they want to forcefully replace the existing alias of the stablecoin contract.

However, at the moment, if the aliases already exists, then `stablecoin-client` crashes at the point it tries to originate the metadata contract (regardless of whether `--replace-alias` was used or not).

Upon some investigation, this seems to due to this morley-client bug: https://gitlab.com/morley-framework/morley/-/issues/896

# To Reproduce

```
$ # clean environment
$ tezos-client forget contract stablecoin-tzip16-metadata && tezos-client forget contract stablecoin

$ stablecoin-client deploy --replace-alias --default-expiry 10 --contract-owner baker --master-minter baker --pauser baker --user baker
Contract was successfully deployed.
Operation hash: oo4aTLQFfM8B747UgSHrAx5itHMT6kyEwMrZE92BkQkfxtA6NRV
Contract address: KT1BDSSUbrWEcaoRr3Y6zyA7vXXS66ZaUk2m
Metadata contract address: KT1NPYNf3dFKiBNTUdXWapjeaoPhgMQGkMVv
Created alias 'stablecoin'.

$ stablecoin-client deploy --replace-alias --default-expiry 10 --contract-owner baker --master-minter baker --pauser baker --user baker
stablecoin-client: Attempted to create an alias that already exists.
```
# Expected behavior

Expected the last command to succeed when `--replace-alias` is used.

Expected the last command to prompt the user when `--replace-alias` is not used.

# Environment

- I noticed this behavior during the #198 upgrade, though this issue has probably been there for a while.

**Comment by lierdakil** [comment]
This was handled by 33844aa28d3b2c63cd98f306d75b283b44584520, verified it indeed fixes the issue.
