### ISSUE TITLE
Cleanup duplicated code from morley-client / morley-metadata

### ISSUE THREAD

**Issue by dcastro** [tqtezos/stablecoin#201]
# Clarification and motivation

During the #198 upgrade, we had to:

* Write code to support `L1AddressOrAlias`, which will be adapted/moved back to `morley-client` here: https://gitlab.com/morley-framework/morley/-/issues/889
* Write a function for running off-chain views via morley-client, which will be moved to `morley-metadata` here: https://gitlab.com/morley-framework/morley-metadata/-/issues/18

When both of these issues are merged & released, we should delete these modules from stablecoin:
* `Stablecoin.Client.L1AddressOrAlias`
* `Stablecoin.Client.Metadata`

Sidenote: while we're here, if https://gitlab.com/morley-framework/morley/-/issues/895 has also been merged, let's also switch to using `getAliasMaybe` [here](https://github.com/tqtezos/stablecoin/blob/bc167c9d043dbcb0d95c297e0b73fde7cf314ee4/haskell/src/Stablecoin/Client/Impl.hs#L381-L387).

# Acceptance criteria

* The two modules above have been deleted

**Comment by lierdakil** [comment]
For reference: `L1AddressOrAlias` was removed in the previous `morley` update, `Metadata` is still around as https://gitlab.com/morley-framework/morley-metadata/-/issues/18 is still open.
