### ISSUE TITLE
Add weeder and hlint checks to CI

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/stablecoin#52]
# Clarification and motivation

We normally want our Haskell code to pass weeder and hlint checks, but this repo doesn't check it on CI.

# Acceptance criteria

CI should fail if Haskell code doesn't pass `hlint` (with our configs) and `weeder` checks.

Note that there is a new [weeder](https://github.com/ocharles/weeder), maybe it's better to use it instead of the old one. The old one is more powerful (it detects unused deps), but it's not deprecated AFAIU. We can even run both, so that we detect as much as possible now and will remove the old one when it's totally dead.

**Comment by gromakovsky** [comment]
Also please cleanup CI config, it has useless lines:
```
# TODO: rewrite it to haskell.nix

env:
  NIX_PATH: nixpkgs=https://github.com/nixos/nixpkgs/archive/b640dbd00877f51616750e347a32fbcb49d2968c.tar.gz
```

**Comment by rvem** [comment]
We'll add new weeder to the CI pipeline in a separate issue once the old weeder will become deprecated
