### ISSUE TITLE
Implement FA2 specific entyrpoints

### ISSUE THREAD

**Issue by awkure** [tqtezos/stablecoin#8]
# Clarification and motivation
It's decided that the contract at least follows FA2 specification, so lets implement the corresponding entrypoints within this issue.

# Acceptance criteria
Entrypoints that are described in the reference [specification](https://gitlab.com/tzip/tzip/-/blob/d3b5e954fd9117a29eb2192efdecba7ea7f3d6c5/proposals/tzip-12/tzip-12.md) are present and tested accordingly

**Comment by gromakovsky** [comment]
We decided that @awkure will implement these entrypoints in LIGO and @sras will _independently_ write tests using our Haskell libraries.
